// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn8eni0VgyFM0jB7gT16lNEbOUfcTJHvo',
    appId: '1:671651083297:web:80fe1e4a27dbd776285f60',
    messagingSenderId: '671651083297',
    projectId: 'hive-f9d01',
    authDomain: 'hive-f9d01.firebaseapp.com',
    storageBucket: 'hive-f9d01.firebasestorage.app',
    measurementId: 'G-06D1810ZCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiMmpwWIE08Ndm4G7tYDwahmgTaoD6quM',
    appId: '1:671651083297:android:fbb6a6f1698c315b285f60',
    messagingSenderId: '671651083297',
    projectId: 'hive-f9d01',
    storageBucket: 'hive-f9d01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM8jjy3uB0gGBexuXTnx769rV1VSeq7Hs',
    appId: '1:671651083297:ios:cf0bf02fd6001b46285f60',
    messagingSenderId: '671651083297',
    projectId: 'hive-f9d01',
    storageBucket: 'hive-f9d01.firebasestorage.app',
    iosBundleId: 'com.collegeevents.collegeEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM8jjy3uB0gGBexuXTnx769rV1VSeq7Hs',
    appId: '1:671651083297:ios:cf0bf02fd6001b46285f60',
    messagingSenderId: '671651083297',
    projectId: 'hive-f9d01',
    storageBucket: 'hive-f9d01.firebasestorage.app',
    iosBundleId: 'com.collegeevents.collegeEvents',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn8eni0VgyFM0jB7gT16lNEbOUfcTJHvo',
    appId: '1:671651083297:web:d80b578316a7c612285f60',
    messagingSenderId: '671651083297',
    projectId: 'hive-f9d01',
    authDomain: 'hive-f9d01.firebaseapp.com',
    storageBucket: 'hive-f9d01.firebasestorage.app',
    measurementId: 'G-FLS3W46YS4',
  );

}